### PR TITLE
bump symfony/debug to include 4.0

### LINKED ISSUE #338: Support for symfony/debug v4 due to conflict with Drush
Currently, I've got `symfony/debug` `v4.0.6` installed as per:

```
$ composer global why symfony/debug -t
symfony/debug v4.0.6 Symfony Debug Component
└──symfony/console v3.4.6 (requires symfony/debug ~2.8|~3.0|~4.0)
   ├──consolidation/annotated-command 2.8.3 (requires symfony/console ^2.8|^3|^4)
   │  └──drush/drush 8.1.16 (requires consolidation/annotated-command ^2.8.1)
   │     └──__root__ (requires drush/drush ~8@stable)
   ├──consolidation/output-formatters 3.2.0 (requires symfony/console ^2.8|^3|^4)
   │  ├──consolidation/annotated-command 2.8.3 (requires consolidation/output-formatters ^3.1.12)
   │  │  └──drush/drush 8.1.16 (requires consolidation/annotated-command ^2.8.1)
   │  │     └──__root__ (requires drush/drush ~8@stable)
   │  └──drush/drush 8.1.16 (requires consolidation/output-formatters ~3)
   │     └──__root__ (requires drush/drush ~8@stable)
   ├──drush/drush 8.1.16 (requires symfony/console ~2.7|^3)
   │  └──__root__ (requires drush/drush ~8@stable)
   └──psy/psysh v0.8.17 (requires symfony/console ~2.3.10|^2.4.2|~3.0|~4.0)
      └──drush/drush 8.1.16 (requires psy/psysh ~0.6)
         └──__root__ (requires drush/drush ~8@stable)
```

So I cannot install the latest version of [`drupal/console`](https://github.com/hechoendrupal/drupal-console) (v1.8) since `drupal/console-core` requires `symfony/debug` `~2.8|~3.0` (but not `~4.0`).

```
$ composer global show -a drupal/console-core | grep debug
symfony/debug ~2.8|~3.0
```

Is there any chance to expand the dependencies to support `symfony/debug` as `~2.8|~3.0|~4.0`? Or drop it from the `composer.json`, since `symfony/debug` is already included with `symfony/console 3.4.6`, e.g.

```
$ composer global show -a symfony/console 3.4.6 | grep debug
symfony/debug ~2.8|~3.0|~4.0
```

----

My error:

```
$ composer global require drupal/console
  Problem 1
    - drupal/console 1.8.0 requires drupal/console-core 1.8.0 -> satisfiable by drupal/console-core[1.8.0].
    - Installation request for drupal/console ^1.8 -> satisfiable by drupal/console[1.8.0].
    - Conclusion: remove symfony/debug v4.0.6
    - Conclusion: don't install symfony/debug v4.0.6
    - drupal/console-core 1.8.0 requires symfony/debug ~2.8|~3.0 -> satisfiable by symfony/debug
...
    - Can only install one of: symfony/debug[v3.4.6, v4.0.6].
    - Installation request for symfony/debug (locked at v4.0.6) -> satisfiable by symfony/debug[v4.0.6].
```

My existing `composer.json`:

```
{
    "require": {
        "drush/drush": "~8@stable"
    }
}
```

### PR DESCRIPTION
**Pull request by greggles**
This would fix #338.

I didn't test anything :)

### CODE REVIEW

**Comment by vorapoap** [comment]
When to merge this to master branch T_T

**Comment by bgronek** [comment]
I would imagine that this is causing issues for a number of folks who want to use Drupal Console.  Any plans to support symfony/debug 4.0?

**Comment by ben-hamelin** [comment]
In addition to the debug requirement I also had to downgrade symfony/finder and symfony/filesystem to their 3.4.* versions

**Comment by LOBsTerr** [comment]
I close PR, because we are already support "symfony/debug": "~3.0|^4.4",

**Pull request closed without merging**
