### PR TITLE
Support new installers location. Avoid infinite loop in translator. Fix #363

### LINKED ISSUE #363: Infinite loop with latest composer/installers
Easy to reproduce, see: https://github.com/drupal-composer/drupal-project/issues/508

Basically I would suggest 2 changes:

- Try to avoid recursive function call if buildCoreLanguageDirectory is called with language `en`. Rather throw an exception.
- Support both locations for language directory

### PR DESCRIPTION
**Pull request by eiriksm**

### CODE REVIEW

**Comment by jmolivas** [comment]
@enzolutions @harold20 can you take a look at this based on a conversation on slack seems like is caused by this change on the `composer/installers` https://github.com/composer/installers/commit/4aa453ad54f76c4db02b6ad3574e17795c51fb23#diff-2cb8fec6869068770a69d146dbcde76b

**Comment by clemens-tolboom** [comment]
See my comment in https://github.com/hechoendrupal/drupal-console/issues/4129#issuecomment-521934906

**Comment by TonyTheFerg** [comment]
Thanks, this fixed a memory error I began receiving when trying to `./drupal module:install MODULE`  after a recent `composer update`

**Comment by dwkitchen** [comment]
The resolved the issues for me as well.

**Comment by rfsbsb** [comment]
I can confirm this fix the problem for me as well.

**Comment by amaisano** [comment]
Should the files in the new location be gitignored?

**Comment by enzolutions** [comment]
Thanks to @eiriksm for the code and the rest of you for testing.

I will accept this PR and create a new release today.

@clemens-tolboom there is something we could to fix the issue in composer/installer of drupal-composer/drupal-project?  BTW thanks for your help in that matter

**Comment by clemens-tolboom** [comment]
> Is there something we could to fix the issue in composer/installer of drupal-composer/drupal-project?

@enzolutions I've tested this commit. Works fine for me. We don't have to do anything right? Unless I missed something.

People have to:

- revert their hotfix from https://github.com/hechoendrupal/drupal-console/issues/4129#issuecomment-522060577
- `rm -rf vendor/drupal/console-en`
- `composer install` which will install console-en into `PROJECT_ROOT/console/language/console-en`

Correct me if I'm wrong.

**Comment by clemens-tolboom** [comment]
Ai ... I forgot to mention installing latest version of `drupal/console` (I did a git pull)

**Comment by jmolivas** [comment]
@clemens-tolboom you will probably want to add `console/language` to your `.gitignore` file.

**Comment by AlexSkrypnyk** [comment]
@jmolivas this "hanging" directory started to appear in all projects that use console after the update. Is it possible to avoid the creation of this dir altogether? Also, how come it is doing it in the root of the repo and not in the `vendor` dir? Is this a bug? Thanks

**Comment by clemens-tolboom** [comment]
AFAIK the idea of the console/language directory is you can add your own translation there and manage those in your own (git) workflow. That is why https://github.com/drupal-composer/drupal-project/issues/509 added it to `.gitignore` to ignore https://github.com/hechoendrupal/drupal-console-en and potential other public translations.

So IMHO it is not a bug.

**Comment by AlexSkrypnyk** [comment]
@clemens-tolboom Thank you for explanation.

Created https://github.com/hechoendrupal/drupal-console-core/issues/366

**Comment by jmolivas** [comment]
This was related to an old PR https://github.com/composer/installers/pull/311 merged to the `composer/installers` repository that is no longer required.

But got fixed on latest release of the drupal-console project
https://github.com/hechoendrupal/drupal-console/releases/tag/1.9.3

**Pull request merged**
